; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = firmware/src
include_dir = firmware/include
lib_dir = firmware/lib
data_dir = firmware/data

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

board_build.filesystem = littlefs
board_build.partitions = firmware/partitions.csv

platform_packages = 
    espressif/toolchain-xtensa-esp32@12.2.0+20230208

build_flags = 
    -std=gnu++23
    -Wl,--no-warn-rwx-segments
    -fdiagnostics-color=always
    -Wno-attributes
build_unflags = 
    -std=gnu++11
    -std=gnu++17

extra_scripts = 
    pre:scripts/generate_version.py
    pre:scripts/generate_compiledb.py
    scripts/upload_config.py
monitor_speed = 115200
monitor_filters = default, log2file, esp32_exception_decoder
monitor_port = COM4
upload_port = COM4

lib_deps =
  esp32async/ESPAsyncWebServer @ ^3.11.2
  bblanchon/ArduinoJson @ ^7.4.3
  knolleary/PubSubClient @ ^2.8
  4-20ma/ModbusMaster @ ^2.0.1
  https://github.com/codeplea/tinyexpr.git